// AUTH
export const LOGIN = "AUTH:LOGIN";
export const LOGGED_IN = "AUTH:LOGGED_IN";
export const CHANGE_LOGIN_FORM = "AUTH:CHANGE_LOGIN_FORM";
export const LOGIN_FAILED = "AUTH:LOGIN_FAILED";
export const LOGOUT = "AUTH:LOGOUT";
export const LOGGED_OUT = "AUTH:LOGGED_OUT";

// USERS
export const SAVE_USER = "USERS:CREATE";
export const LOAD_USERS = "USERS:LOAD_USERS";
export const USERS_LOADED = "USERS:USERS_LOADED";
export const CHANGE_USER_FORM = "USERS:CHANGE_FORM";
export const USER_CREATE_ERROR = "USERS:CREATE_ERRORS";
export const USER_RESET_FORM = "USERS:RESET_FORM";
export const EDIT_USER = "USERS:EDIT";
export const USER_ERROR = "USERS:ERROR";
export const DELETE_USER = "USERS:DELETE";
export const USER_DELETED = "USERS:DELETED";
export const CREATE_USER = "USERS:CREATE";
export const CREATE_USER_FORM = "USERS:CREATE";
export const CONFIRM_USER = "USERS:CONFIRM";
export const REFRESH_USERS = "USERS:REFRESH";
export const CREATE_COMPLETE = "USERS:COMPLETE";
export const USER_CONFIRMED = "USER:CONFIRMED";
export const UPDATE_USER = "USER:UPDATE";
export const USER_UPDATED = "USER:UPDATED";

// REPORTS
export const LOAD_REPORTS = "REPORTS:LOAD";
export const LOAD_DASHBOARD_REPORT = "REPORTS:DASHBOARD_LOAD";
export const REPORTS_LOADED = "REPORTS:LOADED";

// OTHER
export const LOAD_DATA = "DATA:LOAD";

// ERROR/SUCCESS POPUP
export const SHOW_ERROR = "POPUP:ERROR";
export const DISMISS_ERROR = "POPUP:ERROR_DISMISS";

// DIALOG
export const SHOW_DIALOG = "DIALOG:SHOW";
export const CLOSE_DIALOG = "DIALOG:CLOSE";
export const CONFIRM_DIALOG = "DIALOG:CONFIRM";

// FEES
export const GET_FEES = "FEES:GET";
export const UPDATE_FEES = "FEES:UPDATE";
export const RETURN_FEES = "FEES:RETURN";
export const SUBMIT_FEES = "FEES:SUBMIT";
export const SUBMIT_FEES_COMPLETE = "FEES:SUBMIT_COMPLETE";
